### ISSUE TITLE
Indentation for "Gui for motion sensor"

### ISSUE THREAD

**Issue by ofenerci** [wavicles/Plugins-for-ExpEYES#4]
Hello,

I  want to include "Gui for motion sensor" into ExpEYES program. But the program indentation is not correct. When I run the program from ExpEYES-Junior, it gives error due to indentation problem. It is possible to post the new version of it, which has the correct indentation.

Best Regards,
Ozhan

**Comment by wavicles** [comment]
Hi
On 10-Jun-2015 7:32 PM, "Özhan Fenerci" <notifications@github.com> wrote:
>
> Hello,
>
> I want to include "Gui for motion sensor" into ExpEYES program. But the
program indentation is not correct. When I run the program from
ExpEYES-Junior, it gives error due to indentation problem. It is possible
to post the new version of it, which has the correct indentation.

Sure. I will correct the indentation and post the new version.

Thanks and regards
Praveen

**Comment by wavicles** [comment]
Hi Ozhan
I have posted new program Motion-Sensor-GUI.py
Please check. It's working. 
thanks and regards
